services:
  postgres:
    image: postgres:16
    container_name: pipedrive_postgre_db
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_pipedrive
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_pipedrive_postgre:/var/lib/postgresql/data
    restart: always

  cron:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PIPEDRIVE_API_KEY
        - PIPEDRIVE_BASE_URL
        - DB_USER
        - DB_PASSWORD
        - DB_DATABASE
        - TIMEZONE
    container_name: pipedrive_postgre_cron
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    restart: always

volumes:
  db_pipedrive_postgre:
    name: db_pipedrive_postgre