services:
  mysql:
    image: mysql:8.1
    container_name: db_pipedrive
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_pipedrive
    ports:
      - "3310:3306"
    volumes:
      - db_pipedrive:/var/lib/mysql
    restart: always

  cron:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PIPEDRIVE_API_KEY
        - PIPEDRIVE_BASE_URL
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - TIMEZONE
    container_name: pipedrive_cron
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    restart: always

volumes:
  db_pipedrive:
    name: db_pipedrive